version: '2.4'
services: 
  servicename:
    containerName: service-name
    labels:
      key: "value"
    build: 
      context: .
      target: dev
      args: 
        - NPM_TOKEN: your-npm-token
        - PORT: 3000
    ports:
      - "3000:3000"
    volumes: 
      - .:/opt/node_app/app:delegated
      - /node/app/node_modules