version: '2.4'
services: 
  service-name:
    container_name: service-name
    labels:
      - "value"
    build: 
      context: .
      target: dev
      args: 
        - "NPM_TOKEN=npm-token"
        - "PORT=3000"
    # to expose service port uncomment the two following lines
    # ports:
    #   - "3000:3000"
    volumes: 
      - .:/opt/node_app/app:delegated
      - /node/app/node_modules